config/routes.rb
SiteOlimp::Application.routes.draw do
  root :to => "home#index"

  devise_for :users, :controllers  => {
    :registrations => 'users/registrations'
  }, :skip => [:registrations]                                          
    as :user do
      get '/users/sign_up', :to => 'users/registrations#new'
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration' 
      get 'users/:id', :to => 'admin/representantes#index'
      put 'users' => 'devise/registrations#update', :as => 'user_registration' 
      post '/users', :to => 'users/registrations#create'
    end
    
  match '/users/:id', :to => 'users/registrations#destroy',
    :as => :destroy_user, :via => :delete

  match '/representante/inscriptions/inscrever/:id', :to => 'representante/inscriptions#inscrever',
    :as => :inscrever

  post '/representante/inscriptions/efetuar_inscricao/:id',
    :to => 'representante/inscriptions#efetuar_inscricao',
    :as => :efetuar_inscricao

  namespace :representante do 
    resources :athletes 

    match 'inscriptions', :to => 'inscriptions#index'

  end

  namespace :admin do
    resources :competitions, :organizations
    
    match '/representantes', :to => "representantes#index", :as => :representantes
  end

end

app/models/admin/organization.rb
# -*- encoding : utf-8 -*-
class Admin::Organization < ActiveRecord::Base
	has_many :athletes, :class_name=>"Representante::Athlete", :dependent => :destroy
	has_many :users, :class_name=>"User", :dependent => :destroy

	attr_accessible :name

    #tamanho maximo pro nome
    validates_length_of :name, :minimum => 1, :maximum => 40,
     :message => "Campo deve ter entre 1 e 40 caracteres"
end

app/controllers/admin/organizations_controller.rb
# -*- encoding : utf-8 -*-
class Admin::OrganizationsController < ApplicationController

  before_filter :only_admin
  
  # GET /admin/organizations
  # GET /admin/organizations.json
  def index
    @admin_organizations = Admin::Organization.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_organizations }
    end
  end

  # GET /admin/organizations/new
  # GET /admin/organizations/new.json
  def new
    @admin_organization = Admin::Organization.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_organization }
    end
  end

  # GET /admin/organizations/1/edit
  def edit
    @admin_organization = Admin::Organization.find(params[:id])
  end

  # POST /admin/organizations
  # POST /admin/organizations.json
  def create
    @admin_organization = Admin::Organization.new(params[:admin_organization])

    respond_to do |format|
      if @admin_organization.save
        format.html { redirect_to admin_organizations_url, notice: 'Organização criada com sucesso' }
        format.json { render json: @admin_organization, status: :created, location: @admin_organization }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/organizations/1
  # PUT /admin/organizations/1.json
  def update
    @admin_organization = Admin::Organization.find(params[:id])

    respond_to do |format|
      if @admin_organization.update_attributes(params[:admin_organization])
        format.html { redirect_to admin_organizations_url, notice: 'Organização atualizada com sucesso' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/organizations/1
  # DELETE /admin/organizations/1.json
  def destroy
    @admin_organization = Admin::Organization.find(params[:id])
    @admin_organization.destroy

    respond_to do |format|
      format.html { redirect_to admin_organizations_url, notice: 'Organização apagada com sucesso'} 
      format.json { head :no_content }
    end
  end

  private
  def only_admin

    if current_user == nil
      redirect_to root_path, :notice => "Acesso negado" 
    elsif !current_user.is_admin
      redirect_to root_path, :notice => "Acesso negado"  
    end

  end
end

app/helpers/admin/organizations_helper.rb
# -*- encoding : utf-8 -*-
module Admin::OrganizationsHelper
end

app/views/admin/organizations/_form.html.erb
<%= form_for(@admin_organization) do |f| %>
  <% if @admin_organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_organization.errors.count, "error") %> prohibited this admin_organization from being saved:</h2>

      <ul>
      <% @admin_organization.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Nome" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit "Criar/Atualizar dados"%>
  </div>
<% end %>

app/views/admin/organizations/edit.html.erb
<h1>Editando organização</h1>

<%= render 'form' %>

<%= link_to 'Exibir detalhes', @admin_organization %> |
<%= link_to 'Voltar', admin_organizations_path %>

app/views/admin/organizations/index.html.erb
<h2>Organizações</h2>

<% if @admin_organizations.empty? %>
  <p>Nenhuma organização cadastrada</p>
<% else %>
  
  
  <% @admin_organizations.each do |org| %>
    <div class="organization">

      <h3><%= org.name %></h3>

      <% if org.athletes.empty? %>
        <p>Não existem atletas cadastrados nesta organização</p>
      <% else %>

        <h4>Atletas</h4>

        <ul>
          <% org.athletes.each do |atl| %>
            <li><%= atl.details %></li>
          <% end %>
        </ul>

      <% end %>

      <% if org.users.empty? %>
        <p>Não existem representantes cadastrados para esta organização</p>
      <% else %>
        <h4>Representantes</h4>

        <ul>
            <% org.users.each do |reps| %>
              <li><%= reps.email %></li>
            <% end %>
        </ul>  
      <% end %>       

      <p class="links">
        <%= link_to 'Editar', edit_admin_organization_path(org) %> |
        <%= link_to 'Apagar', org, confirm: 'Tem certeza disso?', method: :delete %>
      </p>
      
    </div>
    <hr/>
  <% end %>
  
<% end %>

<br />

<%= link_to 'Nova organização', new_admin_organization_path %>

app/views/admin/organizations/new.html.erb
<h1>Nova organização</h1>

<%= render 'form' %>

<%= link_to 'Voltar', admin_organizations_path %>

app/views/admin/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @admin_organization.name %>
</p>


<%= link_to 'Edit', edit_admin_organization_path(@admin_organization) %> |
<%= link_to 'Back', admin_organizations_path %>