config/routes.rb
SiteOlimp::Application.routes.draw do
  root :to => "home#index"

  devise_for :users, :controllers  => {
    :registrations => 'users/registrations'
  }, :skip => [:registrations]                                          
    as :user do
      get '/users/sign_up', :to => 'users/registrations#new'
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration' 
      get 'users/:id', :to => 'admin/representantes#index'
      put 'users' => 'devise/registrations#update', :as => 'user_registration' 
      post '/users', :to => 'users/registrations#create'
    end
    
  match '/users/:id', :to => 'users/registrations#destroy',
    :as => :destroy_user, :via => :delete

  match '/representante/inscriptions/inscrever/:id', :to => 'representante/inscriptions#inscrever',
    :as => :inscrever

  post '/representante/inscriptions/efetuar_inscricao/:id',
    :to => 'representante/inscriptions#efetuar_inscricao',
    :as => :efetuar_inscricao

  namespace :representante do 
    resources :athletes 

    match 'inscriptions', :to => 'inscriptions#index'

  end

  namespace :admin do
    resources :competitions, :organizations
    
    match '/representantes', :to => "representantes#index", :as => :representantes
  end

end

app/models/representante.rb
# -*- encoding : utf-8 -*-
module Representante
  def self.table_name_prefix
    'representante_'
  end
end

app/models/representante/athlete.rb
# -*- encoding : utf-8 -*-
class Representante::Athlete < ActiveRecord::Base
	belongs_to :organization, :class_name=>"Admin::Organization"
	has_and_belongs_to_many :competitions, :class_name=>"Admin::Competition",
	 :join_table => 'athletes_competitions'
	 
	attr_accessible :age, :name, :sex

	validates_presence_of :name

	#validacao numerica
	validates :age, :numericality => { :greater_than => 0,
	:message => "Apenas números maiores que 0 são permitidos" }

	#apenas masculino e feminino aceitos
	validates :sex, :inclusion => { :in => %w(Masculino Feminino),
    :message => "\"%{value}\" não é um valor válido para o sexo" }

	def details
		return name << " - " << age.to_s << " anos - " << sex
	end

	def can_join(comp)
		return (sex == comp.sex) && (age.between?(comp.min_age, comp.max_age))
	end
end

app/controllers/admin/representantes_controller.rb
# -*- encoding : utf-8 -*-
class Admin::RepresentantesController < ApplicationController

	before_filter :only_admin

	def index
		@admin_representantes = User.where(:is_admin => false)

		respond_to do |format|
      		format.html # index.html.erb
      		format.json { render json: @admin_representantes }
    	end
	end

	private
  	def only_admin

    	if current_user == nil
      		redirect_to root_path, :notice => "Acesso negado" 
    	elsif !current_user.is_admin
      		redirect_to root_path, :notice => "Acesso negado"  
    	end

  	end

end

app/controllers/representante/athletes_controller.rb
# -*- encoding : utf-8 -*-
class Representante::AthletesController < ApplicationController

  before_filter :only_rep
  before_filter :same_org, :only => [:show, :edit, :update, :destroy]

  # GET /representante/athletes
  # GET /representante/athletes.json
  def index
    @representante_athletes = current_user.organization.athletes

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @representante_athletes }
    end
  end

  # GET /representante/athletes/1
  # GET /representante/athletes/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @representante_athlete }
    end
  end

  # GET /representante/athletes/new
  # GET /representante/athletes/new.json
  def new
    @representante_athlete = Representante::Athlete.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @representante_athlete }
    end
  end

  # GET /representante/athletes/1/edit
  def edit
  end

  # POST /representante/athletes
  # POST /representante/athletes.json
  def create
    @representante_athlete = Representante::Athlete.new(params[:representante_athlete])
    @representante_athlete.organization = current_user.organization

    respond_to do |format|
      if @representante_athlete.save
        format.html { redirect_to representante_athletes_url, notice: 'Atleta criado com sucesso' }
        format.json { render json: @representante_athlete, status: :created, location: @representante_athlete }
      else
        format.html { render action: "new" }
        format.json { render json: @representante_athlete.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /representante/athletes/1
  # PUT /representante/athletes/1.json
  def update
    respond_to do |format|
      if @representante_athlete.update_attributes(params[:representante_athlete])
        format.html { redirect_to representante_athletes_url, notice: 'Atleta atualizado com sucesso' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @representante_athlete.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /representante/athletes/1
  # DELETE /representante/athletes/1.json
  def destroy
    @representante_athlete = Representante::Athlete.find(params[:id])
    @representante_athlete.destroy

    respond_to do |format|
      format.html { redirect_to representante_athletes_url, notice: 'Atleta apagado com sucesso' }
      format.json { head :no_content }
    end
  end

  private

  def only_rep

    if current_user == nil
      redirect_to root_path, :notice => "Acesso negado" 
    elsif current_user.is_admin
      redirect_to root_path, :notice => "Acesso negado"  
    end

  end

  def same_org
    @representante_athlete = Representante::Athlete.find(params[:id])

    if current_user.organization != @representante_athlete.organization
      redirect_to representante_athletes_url, :notice => "Acesso negado"
    end
    
  end
end

app/controllers/representante/inscriptions_controller.rb
# -*- encoding : utf-8 -*-
class Representante::InscriptionsController < ApplicationController

	def index
		@athletes = Representante::Athlete.where(
			:organization_id => current_user.organization.id)
		@competitions = Admin::Competition.all
	end

	def inscrever
		@athletes = Representante::Athlete.where(
			:organization_id => current_user.organization.id)
		@competition = Admin::Competition.find(params[:id])
	end

	def efetuar_inscricao
		@competition = Admin::Competition.find(params[:id])

		if (not params[:competition].nil?) &&
			(params[:competition][:athletes_ids].count > @competition.max_per_org)
			flash[:notice] = "Apenas #{@competition.max_per_org} atletas são permitidos nessa competição"
	    	redirect_to :back
	    	return
	    end

		respond_to do |format|

			@competition.athletes.delete_if {|atl| atl.organization.id == current_user.organization.id}

			if (not params[:competition].nil?)

				params[:competition][:athletes_ids].each do |id|
					atl = Representante::Athlete.find(id)
					@competition.athletes << atl
				end

			end

	    	format.html { redirect_to :back, notice: 'Inscrição atualizada.' }
	    end
	end

end

app/helpers/admin/representantes_helper.rb
# -*- encoding : utf-8 -*-
module Admin::RepresentantesHelper
end

app/helpers/representante/athletes_helper.rb
# -*- encoding : utf-8 -*-
module Representante::AthletesHelper
end

app/helpers/representante/inscriptions_helper.rb
# -*- encoding : utf-8 -*-
module Representante::InscriptionsHelper
end

app/views/representante/athletes/_form.html.erb
<%= form_for(@representante_athlete) do |f| %>
  <% if @representante_athlete.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@representante_athlete.errors.count, "error") %> prohibited this representante_athlete from being saved:</h2>

      <ul>
      <% @representante_athlete.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Nome" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age, "Idade" %><br />
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :sex, "Sexo" %><br />
    <%= f.select :sex, options_for_select([["Masculino", "Masculino"],
     ["Feminino", "Feminino"]]) %>
  </div>
  <div class="actions">
    <%= f.submit "Criar/atualizar dados"%>
  </div>
<% end %>

app/views/representante/athletes/edit.html.erb
<h2>Editando atleta</h2>

<%= render 'form' %>

<%= link_to 'Exibir detalhes', @representante_athlete %> |
<%= link_to 'Voltar', representante_athletes_path %>

app/views/representante/athletes/index.html.erb
<h2>Atletas - <%= current_user.organization.name %></h2>

<% if @representante_athletes.empty? %>
  <p>Nenhum atleta cadastrado</p>
<% else %>
  <ul>
    <% @representante_athletes.each do |atl| %>
      <li><%= atl.details %> | <%= link_to 'Apagar atleta', atl, confirm: 'Tem certeza disso?', method: :delete %></li>        
      </p>
    <% end %>
  </ul>
<% end %>

<br />

<%= link_to 'Novo atleta', new_representante_athlete_path %>

app/views/representante/athletes/new.html.erb
<h2>Novo atleta</h2>

<%= render 'form' %>

<%= link_to 'Voltar', representante_athletes_path %>

app/views/representante/athletes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @representante_athlete.name %>
</p>

<p>
  <b>Sex:</b>
  <%= @representante_athlete.sex %>
</p>

<p>
  <b>Age:</b>
  <%= @representante_athlete.age %>
</p>

<p>
  <b>Organization:</b>
  <%= @representante_athlete.organization.name %>
</p>


<%= link_to 'Editar', edit_representante_athlete_path(@representante_athlete) %> |
<%= link_to 'Voltar', representante_athletes_path %>