config/routes.rb
SiteOlimp::Application.routes.draw do
  root :to => "home#index"

  devise_for :users, :controllers  => {
    :registrations => 'users/registrations'
  }, :skip => [:registrations]                                          
    as :user do
      get '/users/sign_up', :to => 'users/registrations#new'
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration' 
      get 'users/:id', :to => 'admin/representantes#index'
      put 'users' => 'devise/registrations#update', :as => 'user_registration' 
      post '/users', :to => 'users/registrations#create'
    end
    
  match '/users/:id', :to => 'users/registrations#destroy',
    :as => :destroy_user, :via => :delete

  match '/representante/inscriptions/inscrever/:id', :to => 'representante/inscriptions#inscrever',
    :as => :inscrever

  post '/representante/inscriptions/efetuar_inscricao/:id',
    :to => 'representante/inscriptions#efetuar_inscricao',
    :as => :efetuar_inscricao

  namespace :representante do 
    resources :athletes 

    match 'inscriptions', :to => 'inscriptions#index'

  end

  namespace :admin do
    resources :competitions, :organizations
    
    match '/representantes', :to => "representantes#index", :as => :representantes
  end

end

app/models/admin/competition.rb
# -*- encoding : utf-8 -*-
class Admin::Competition < ActiveRecord::Base
	has_and_belongs_to_many :athletes, :class_name=>"Representante::Athlete",
	 :join_table => 'athletes_competitions'

	attr_accessible :max_age, :min_age, :name, :sex, :max_per_org, :athletes_ids

	#validacao de apenas numeros
	validates :max_age, :numericality => { :greater_than => 0,
	:message => "Apenas números maiores que 0 são permitidos" }
	validates :min_age, :numericality => { :greater_than => 0,
	:message => "Apenas números maiores que 0 são permitidos" }
    validates :max_per_org, :numericality => { :greater_than => 0,
	:message => "Apenas números maiores que 0 são permitidos" }

	#apenas masculino e feminino aceitos
	validates :sex, :inclusion => { :in => %w(Masculino Feminino),
    :message => "%{value} não é um valor válido para o sexo" }

    #validando presença
    validates_presence_of :name, :message => "Campo obrigatório"

    validate :idades_min_max

	def full_name
		return "" << name.to_s << " (" << min_age.to_s << " a " <<
		  max_age.to_s << " anos) " << " - " << sex.to_s << " - " <<
			max_per_org.to_s << " atletas por organização"
	end

	private
	def idades_min_max

		if !(max_age && min_age)
			return
		end

		if max_age < min_age
			errors.add(:max_age, "Idade máxima deve ser maior que a mínima") 
		end
	end
end

app/controllers/admin/competitions_controller.rb
# -*- encoding : utf-8 -*-
class Admin::CompetitionsController < ApplicationController

  before_filter :only_admin

  # GET /admin/competitions
  # GET /admin/competitions.json
  def index
    @admin_competitions = Admin::Competition.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_competitions }
    end
  end

  # GET /admin/competitions/1
  # GET /admin/competitions/1.json
  def show
    @admin_competition = Admin::Competition.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_competition }
    end
  end

  # GET /admin/competitions/new
  # GET /admin/competitions/new.json
  def new
    @admin_competition = Admin::Competition.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_competition }
    end
  end

  # GET /admin/competitions/1/edit
  def edit
    @admin_competition = Admin::Competition.find(params[:id])
  end

  # POST /admin/competitions
  # POST /admin/competitions.json
  def create
    @admin_competition = Admin::Competition.new(params[:admin_competition])

    respond_to do |format|
      if @admin_competition.save
        format.html { redirect_to admin_competitions_url, notice: 'Competição cadastrada com sucesso' }
        format.json { render json: @admin_competition, status: :created, location: @admin_competition }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/competitions/1
  # PUT /admin/competitions/1.json
  def update
    @admin_competition = Admin::Competition.find(params[:id])

    respond_to do |format|
      if @admin_competition.update_attributes(params[:admin_competition])
        format.html { redirect_to admin_competitions_url, notice: 'Competição atualizada com sucesso' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/competitions/1
  # DELETE /admin/competitions/1.json
  def destroy
    @admin_competition = Admin::Competition.find(params[:id])
    @admin_competition.destroy

    respond_to do |format|
      format.html { redirect_to admin_competitions_url, notice: 'Competição apagada com sucesso' }
      format.json { head :no_content }
    end
  end

  private
  def only_admin

    if current_user == nil
      redirect_to root_path, :notice => "Acesso negado" 
    elsif !current_user.is_admin
      redirect_to root_path, :notice => "Acesso negado"  
    end

  end
end

app/helpers/admin/competitions_helper.rb
# -*- encoding : utf-8 -*-
module Admin::CompetitionsHelper
end

app/views/admin/competitions/_form.html.erb
<%= form_for(@admin_competition) do |f| %>
  <% if @admin_competition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_competition.errors.count, "error") %> prohibited this admin_competition from being saved:</h2>

      <ul>
      <% @admin_competition.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Nome" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :min_age, "Idade mínima" %><br />
    <%= f.number_field :min_age %>
  </div>
  <div class="field">
    <%= f.label :max_age, "Idade máxima" %><br />
    <%= f.number_field :max_age %>
  </div>
  <div class="field">
    <%= f.label :max_per_org, "Inscrições máximas por organização" %><br />
    <%= f.number_field :max_per_org %>
  </div>
  <div class="field">
    <%= f.label :sex, "Sexo" %><br />
    <%= f.select :sex, options_for_select([["Masculino", "Masculino"],
     ["Feminino", "Feminino"]]) %>
  </div>
  <div class="actions">
    <%= f.submit "Criar/Atualizar dados" %>
  </div>
<% end %>

app/views/admin/competitions/edit.html.erb
<h2>Editando competição</h1>

<%= render 'form' %>

<%= link_to 'Exibir detalhes', @admin_competition %> |
<%= link_to 'Voltar', admin_competitions_path %>

app/views/admin/competitions/index.html.erb
<h2>Competições</h2>

<% if @admin_competitions.empty? %>
  <p>Nenhuma competição cadastrada</p>
<% else %>
  <% @admin_competitions.each do |admin_competition| %>
    <div class="competicao">
      <h3><%= admin_competition.full_name %></h3>

      <% if admin_competition.athletes.empty? %>
        <p>Nenhum atleta cadastrado nesta competição</p>
      <% else %>
        <ul>

          <% admin_competition.athletes.each do |athlete| %>
            <li><strong><%= athlete.organization.name %></strong> | <%= athlete.details %></li>
          <% end %>

        </ul>
      <% end %>

      <p class="links">
        <%= link_to 'Exibir detalhes', admin_competition %> |
        <%= link_to 'Editar', edit_admin_competition_path(admin_competition) %> |
        <%= link_to 'Apagar', admin_competition, confirm: 'Tem certeza disso?', method: :delete %>
      </p>
    </div>

  <% end %>

<% end %>

<br />


<%= link_to 'Nova competição', new_admin_competition_path %>

app/views/admin/competitions/new.html.erb
<h2>Nova competição</h2>

<%= render 'form' %>

<%= link_to 'Voltar', admin_competitions_path %>

app/views/admin/competitions/show.html.erb
<p id="notice"><%= notice %></p>

  <div class="competicao">
    <h3><%= @admin_competition.full_name %></h3>

    <% if @admin_competition.athletes.empty? %>
      <p>Nenhum atleta cadastrado nesta competição</p>
    <% else %>
      <ul>

        <% @admin_competition.athletes.each do |athlete| %>
          <li><strong><%= athlete.organization.name %></strong> | <%= athlete.details %></li>
        <% end %>

      </ul>
    <% end %>

  </div>


<%= link_to 'Editar competição', edit_admin_competition_path(@admin_competition) %> |
<%= link_to 'Voltar', admin_competitions_path %>