config/routes.rb
SiteOlimp::Application.routes.draw do
  root :to => "home#index"

  devise_for :users, :controllers  => {
    :registrations => 'users/registrations'
  }, :skip => [:registrations]                                          
    as :user do
      get '/users/sign_up', :to => 'users/registrations#new'
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration' 
      get 'users/:id', :to => 'admin/representantes#index'
      put 'users' => 'devise/registrations#update', :as => 'user_registration' 
      post '/users', :to => 'users/registrations#create'
    end
    
  match '/users/:id', :to => 'users/registrations#destroy',
    :as => :destroy_user, :via => :delete

  match '/representante/inscriptions/inscrever/:id', :to => 'representante/inscriptions#inscrever',
    :as => :inscrever

  post '/representante/inscriptions/efetuar_inscricao/:id',
    :to => 'representante/inscriptions#efetuar_inscricao',
    :as => :efetuar_inscricao

  namespace :representante do 
    resources :athletes 

    match 'inscriptions', :to => 'inscriptions#index'

  end

  namespace :admin do
    resources :competitions, :organizations
    
    match '/representantes', :to => "representantes#index", :as => :representantes
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Olímpiadas infantis 2012</title>
  <link href='http://fonts.googleapis.com/css?family=Oregano' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% #nao sei onde colocar isso, vai aqui mesmo %>
	<% if user_signed_in? %>
	<% 	if current_user.is_admin %>
	<%   @set_span = "span5" %>
	<%	 @set_span2 = "span7" %>
	<%	else %>
	<%   @set_span = "span8" %>
	<%	 @set_span2 = "span4" %>
	<%	end %>
	<% end %>

	<div id="tudo">
		<header>
			<% if user_signed_in? %>
				<div class="logado">
					<div class="container">

						<div class="row">
						
							<div class="<%= @set_span %> bb">
								<p class="detalhes">
									<%= truncate(current_user.details, :length => 100) %>
								</p>
							</div>

							<div class="<%= @set_span2 %>">
								<ul id="menu">

									<% if current_user.is_admin %>
										<li><%= link_to 'Gerenciar Competições', admin_competitions_path %></li> |
										<li><%= link_to 'Gerenciar Representantes', 
											admin_representantes_path %></li> |
										<li><%= link_to 'Gerenciar Organizações', admin_organizations_path %></li> |
									<% else %>
										<li><%= link_to 'Gerenciar Atletas', representante_athletes_path %></li> |
										<li><%= link_to 'Inscrever atletas', '
										/representante/inscriptions' %></li> |
									<% end %>

									<li><%= link_to('Sair', destroy_user_session_path, :method => :delete) %></li>
								</ul>
							</div>

						</div>
					</div>
				</div>	
			<% end %>		

			<div class="container">			
				<div class="row">

					<div class="span7 nav">
						<nav>
							<ul>
								<li><a href="/">Home</a></li>
								<% if !user_signed_in? %>
									<li><%= link_to('Entrar', new_user_session_path)  %> </li> 
  								<% else %>
  									<li><%= link_to 'Mudar senha',edit_user_registration_path %></li>
  								<% end %>
							</ul>
						</nav>
					</div>

					<div class="span5 title">
						<h1>Olimpíadas infantis</h1>
					</div>

				</div>

			</div>

		</header>

		<div class="fundo_corpo">
			<div class="container corpo box-shadow">

				<p class="notice"><%= notice %></p> 
				<p class="alert"><%= alert %></p> 

				<%= yield %>

			</div>
		</div>

		<footer>
			<div class="container">
				<div class="row">
					<div class="span12">
						<p>Lorem ipsum sit dolor amet - 2012</p>
					</div>
				</div>
			</div>
		</footer>
	</div>

</body>
</html>